<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />	  
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenCvSharpEx\OpenCvSharpEx.csproj" />
  </ItemGroup>
</Project>
